# Generated by Django 5.1.6 on 2025-03-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
