# Generated by Django 5.1.6 on 2025-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_wallet_options_remove_transaction_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumbersCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_code', models.CharField(max_length=16)),
                ('name_bank', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
