# Generated by Django 5.1.6 on 2026-01-30 20:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('sub_title', models.CharField(max_length=255, verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_sliders_image, verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اسلایدر ',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
