# Generated by Django 5.1.6 on 2025-09-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر ', 'verbose_name_plural': 'اسلایدر ها'},
        ),
    ]
