# Generated by Django 5.1.6 on 2025-10-04 17:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_slider_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_sliders_image, verbose_name='تصویر'),
        ),
    ]
