# Generated by Django 5.1.6 on 2025-12-31 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('key', models.SlugField(unique=True, verbose_name='کلید')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('duration_days', models.PositiveIntegerField(verbose_name='زمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='مثلا: دارد / ندارد / 5 / نامحدود', max_length=100)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.feature', verbose_name='ویژگی')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='landing.plan', verbose_name='پلن')),
            ],
            options={
                'unique_together': {('plan', 'feature')},
            },
        ),
    ]
