# Generated by Django 5.1.6 on 2025-02-18 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پکیج')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت کل')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='business.business', verbose_name='کسب\u200cوکار')),
                ('services', models.ManyToManyField(related_name='packages', to='business.service', verbose_name='سرویس\u200cها')),
            ],
            options={
                'verbose_name': 'پکیج',
                'verbose_name_plural': 'پکیج\u200cها',
            },
        ),
    ]
