# Generated by Django 5.1.6 on 2026-02-08 11:11

import django.db.models.deletion
import packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پکیج')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت کل')),
                ('image', models.ImageField(blank=True, null=True, upload_to=packages.models.upload_package_image, verbose_name='تصویر')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='business.business', verbose_name='کسب\u200cوکار')),
                ('services', models.ManyToManyField(related_name='packages', to='business.service', verbose_name='سرویس\u200cها')),
            ],
            options={
                'verbose_name': 'پکیج',
                'verbose_name_plural': 'پکیج\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=1, verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.package', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'نظر پکیج',
                'verbose_name_plural': 'نظرات پکیج',
            },
        ),
    ]
