# Generated by Django 5.1.6 on 2025-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
