# Generated by Django 5.1.6 on 2025-02-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_media_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='media_files',
            field=models.FileField(blank=True, default=list, upload_to='', verbose_name='تصاویر و ویدیوها'),
        ),
    ]
