# Generated by Django 5.1.6 on 2025-04-28 12:53

import packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_packagereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=packages.models.upload_package_image, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='package',
            name='media_files',
            field=models.FileField(blank=True, default=list, upload_to=packages.models.upload_package_image, verbose_name='تصاویر و ویدیوها'),
        ),
    ]
