# Generated by Django 5.1.6 on 2025-05-02 13:51

import packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_media_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='media_files',
            field=models.FileField(blank=True, null=True, upload_to=packages.models.upload_package_image, verbose_name='تصاویر و ویدیوها'),
        ),
    ]
