# Generated by Django 5.1.6 on 2025-05-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_package_media_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='media_files',
        ),
    ]
