# Generated by Django 5.1 on 2025-02-05 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='زمان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('canceled', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.employee', verbose_name='کارمند')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.service', verbose_name='سرویس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'دوشنبه'), ('Tuesday', 'سه\u200cشنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنج\u200cشنبه'), ('Friday', 'جمعه'), ('Saturday', 'شنبه'), ('Sunday', 'یکشنبه')], max_length=10, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='business.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'زمانبندی',
                'verbose_name_plural': 'زمانبندی\u200cها',
            },
        ),
    ]
