# Generated by Django 5.1.6 on 2026-01-30 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('canceled', 'لغو شده')], default='confirmed', max_length=10, verbose_name='وضعیت')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری ارسال شده')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.employee', verbose_name='کارمند')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.service', verbose_name='سرویس')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.availabletimeslot', verbose_name='بازه زمانی')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
            },
        ),
    ]
