# Generated by Django 5.1.6 on 2025-02-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='business.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'زمان در دسترس',
                'verbose_name_plural': 'زمان\u200cهای در دسترس',
            },
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
