# Generated by Django 5.1.6 on 2025-02-25 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('reservations', '0002_availabletime_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='ساعت در دسترس')),
                ('is_booked', models.BooleanField(default=False, verbose_name='رزرو شده')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='business.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'ساعت در دسترس',
                'verbose_name_plural': 'ساعت\u200cهای در دسترس',
                'unique_together': {('service', 'date', 'time')},
            },
        ),
        migrations.DeleteModel(
            name='AvailableTime',
        ),
    ]
