# Generated by Django 5.1.6 on 2025-05-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_employeeschedule_delete_availabletimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه'), (5, 'پنچشنبه'), (6, 'جمعه')], verbose_name='روز هفته'),
        ),
    ]
