# Generated by Django 5.1.6 on 2025-05-26 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_business_type'),
        ('reservations', '0005_alter_employeeschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.employee'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')]),
        ),
    ]
