# Generated by Django 5.1.6 on 2025-05-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_employeeschedule_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
    ]
