# Generated by Django 5.1.6 on 2025-12-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('canceled', 'لغو شده')], default='confirmed', max_length=10, verbose_name='وضعیت'),
        ),
    ]
