# Generated by Django 5.1.6 on 2025-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو'),
        ),
    ]
