# Generated by Django 5.1.6 on 2026-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='روز')),
                ('opening_time', models.TimeField(verbose_name='ساعت شروع')),
                ('closing_time', models.TimeField(verbose_name='ساعت پایان')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعت های کاری',
            },
        ),
    ]
