# Generated by Django 5.1 on 2025-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='closing_time',
            field=models.TimeField(verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج\u200cشنبه', 'پنج\u200cشنبه'), ('جمعه', 'جمعه')], max_length=10, unique=True, verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='opening_time',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
    ]
