# Generated by Django 5.1.6 on 2025-04-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_hours', '0002_alter_workinghours_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.DateField(unique=True, verbose_name='روز'),
        ),
    ]
