# Generated by Django 5.1.6 on 2025-09-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_hours', '0003_alter_workinghours_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'ساعت کاری', 'verbose_name_plural': 'ساعت های کاری'},
        ),
    ]
