# Generated by Django 5.1.6 on 2026-02-08 11:11

import business.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('is_available', models.BooleanField(default=True, verbose_name='قابل رزرو')),
            ],
            options={
                'verbose_name': 'زمان قابل رزرو',
                'verbose_name_plural': 'زمان\u200cهای قابل رزرو',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کسب\u200cوکار')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('business_type', models.CharField(choices=[('salon', 'آرایشگاه')], max_length=20, verbose_name='نوع کسب\u200cوکار')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('telephone_number', models.CharField(max_length=15, verbose_name='تلفن ثابت')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('is_coffee_shop', models.BooleanField(default=False, verbose_name='کافی\u200cشاپ')),
                ('is_parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('random_code', models.CharField(default=business.models.generate_unique_random_code, max_length=10, unique=True, verbose_name='کد تصادفی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار',
                'verbose_name_plural': 'کسب\u200cوکارها',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سرویس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('duration', models.DurationField(verbose_name='مدت زمان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع تست')),
                ('trial_end', models.DateTimeField(default=business.models.default_trial_end, verbose_name='پایان تست')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
            },
        ),
    ]
