# Generated by Django 5.1.6 on 2025-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('آرایشگاه', 'آرایشگاه'), ('مراکز پوست', 'مراکز پوست')], max_length=20, verbose_name='نوع کسب\u200cوکار'),
        ),
    ]
