# Generated by Django 5.1.6 on 2025-05-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('is_booked', models.BooleanField(default=False, verbose_name='رزرو شده؟')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='business.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='business.service')),
            ],
            options={
                'verbose_name': 'ساعت در دسترس',
                'verbose_name_plural': 'ساعات در دسترس',
                'unique_together': {('employee', 'date', 'start_time')},
            },
        ),
    ]
