# Generated by Django 5.1.6 on 2025-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_availabletimeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availabletimeslot',
            unique_together={('service', 'date', 'start_time')},
        ),
        migrations.AlterField(
            model_name='availabletimeslot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='availabletimeslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='availabletimeslot',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.RemoveField(
            model_name='availabletimeslot',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='availabletimeslot',
            name='end_time',
        ),
    ]
