# Generated by Django 5.1.6 on 2025-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_availabletimeslot_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletimeslot',
            options={},
        ),
        migrations.RemoveField(
            model_name='availabletimeslot',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='availabletimeslot',
            name='status',
        ),
        migrations.AddField(
            model_name='availabletimeslot',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='availabletimeslot',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='availabletimeslot',
            name='start_time',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
    ]
