# Generated by Django 5.1.6 on 2025-09-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_availabletimeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletimeslot',
            options={'verbose_name': 'ساعت دردسترس', 'verbose_name_plural': 'ساعت های دردسترس'},
        ),
    ]
