# Generated by Django 5.1.6 on 2026-01-22 13:47

import business.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_availabletimeslot_options'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع آزمایشی')),
                ('trial_end', models.DateTimeField(default=business.models.default_trial_end, verbose_name='پایان آزمایشی')),
                ('active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business', verbose_name='کسب\u200cوکار')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.plan', verbose_name='پلن خریداری شده')),
            ],
        ),
    ]
